apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyAllK8s
metadata:
  name: denyallk8s
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters: {}
  enforcementAction: deny
